"""add conversation models

Revision ID: 8320d3e24dd7
Revises: 4858716f5228
Create Date: 2026-02-05 17:35:01.159849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8320d3e24dd7'
down_revision: Union[str, None] = '4858716f5228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_sessions_user_id'), 'conversation_sessions', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_consumed', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_agent_used'), 'conversation_messages', ['agent_used'], unique=False)
    op.create_index(op.f('ix_conversation_messages_role'), 'conversation_messages', ['role'], unique=False)
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_timestamp'), 'conversation_messages', ['timestamp'], unique=False)
    op.alter_column('risks', 'risk_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               comment='Identificador único del riesgo (ej: RISK-2026-001)',
               existing_nullable=False)
    op.alter_column('risks', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Título descriptivo del riesgo',
               existing_nullable=False)
    op.alter_column('risks', 'description',
               existing_type=sa.TEXT(),
               comment='Descripción detallada del riesgo',
               existing_nullable=False)
    op.alter_column('risks', 'severity',
               existing_type=postgresql.ENUM('critical', 'high', 'medium', 'low', name='riskseverity'),
               comment='Severidad del riesgo: critical, high, medium, low',
               existing_nullable=False)
    op.alter_column('risks', 'likelihood',
               existing_type=postgresql.ENUM('high', 'medium', 'low', name='risklikelihood'),
               comment='Probabilidad de ocurrencia: high, medium, low',
               existing_nullable=False)
    op.alter_column('risks', 'impact_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Score de impacto en escala 0.0-10.0',
               existing_nullable=False)
    op.alter_column('risks', 'status',
               existing_type=postgresql.ENUM('open', 'in_progress', 'mitigated', 'accepted', name='riskstatus'),
               server_default='open',
               comment='Estado actual: open, in_progress, mitigated, accepted',
               existing_nullable=False)
    op.alter_column('risks', 'category',
               existing_type=postgresql.ENUM('technical', 'operational', 'compliance', name='riskcategory'),
               comment='Categoría: technical, operational, compliance',
               existing_nullable=False)
    op.alter_column('risks', 'assigned_to',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment='Email del responsable asignado')
    op.alter_column('risks', 'mitigation_plan',
               existing_type=sa.TEXT(),
               nullable=True,
               comment='Plan detallado de mitigación')
    op.alter_column('risks', 'deadline',
               existing_type=sa.DATE(),
               nullable=True,
               comment='Fecha límite para mitigación')
    op.drop_index(op.f('ix_risks_created_at'), table_name='risks')
    op.drop_constraint(op.f('risks_risk_number_key'), 'risks', type_='unique')
    op.create_index(op.f('ix_risks_category'), 'risks', ['category'], unique=False)
    op.create_index(op.f('ix_risks_deadline'), 'risks', ['deadline'], unique=False)
    op.create_index(op.f('ix_risks_likelihood'), 'risks', ['likelihood'], unique=False)
    op.create_index(op.f('ix_risks_risk_number'), 'risks', ['risk_number'], unique=True)
    op.create_index(op.f('ix_risks_title'), 'risks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risks_title'), table_name='risks')
    op.drop_index(op.f('ix_risks_risk_number'), table_name='risks')
    op.drop_index(op.f('ix_risks_likelihood'), table_name='risks')
    op.drop_index(op.f('ix_risks_deadline'), table_name='risks')
    op.drop_index(op.f('ix_risks_category'), table_name='risks')
    op.create_unique_constraint(op.f('risks_risk_number_key'), 'risks', ['risk_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_risks_created_at'), 'risks', ['created_at'], unique=False)
    op.alter_column('risks', 'deadline',
               existing_type=sa.DATE(),
               nullable=False,
               comment=None,
               existing_comment='Fecha límite para mitigación')
    op.alter_column('risks', 'mitigation_plan',
               existing_type=sa.TEXT(),
               nullable=False,
               comment=None,
               existing_comment='Plan detallado de mitigación')
    op.alter_column('risks', 'assigned_to',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='Email del responsable asignado')
    op.alter_column('risks', 'category',
               existing_type=postgresql.ENUM('technical', 'operational', 'compliance', name='riskcategory'),
               comment=None,
               existing_comment='Categoría: technical, operational, compliance',
               existing_nullable=False)
    op.alter_column('risks', 'status',
               existing_type=postgresql.ENUM('open', 'in_progress', 'mitigated', 'accepted', name='riskstatus'),
               server_default=None,
               comment=None,
               existing_comment='Estado actual: open, in_progress, mitigated, accepted',
               existing_nullable=False)
    op.alter_column('risks', 'impact_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Score de impacto en escala 0.0-10.0',
               existing_nullable=False)
    op.alter_column('risks', 'likelihood',
               existing_type=postgresql.ENUM('high', 'medium', 'low', name='risklikelihood'),
               comment=None,
               existing_comment='Probabilidad de ocurrencia: high, medium, low',
               existing_nullable=False)
    op.alter_column('risks', 'severity',
               existing_type=postgresql.ENUM('critical', 'high', 'medium', 'low', name='riskseverity'),
               comment=None,
               existing_comment='Severidad del riesgo: critical, high, medium, low',
               existing_nullable=False)
    op.alter_column('risks', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descripción detallada del riesgo',
               existing_nullable=False)
    op.alter_column('risks', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Título descriptivo del riesgo',
               existing_nullable=False)
    op.alter_column('risks', 'risk_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Identificador único del riesgo (ej: RISK-2026-001)',
               existing_nullable=False)
    op.drop_index(op.f('ix_conversation_messages_timestamp'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_role'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_agent_used'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_conversation_sessions_user_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    # ### end Alembic commands ###
