"""add incident response model

Revision ID: 908bd075fcff
Revises: 8320d3e24dd7
Create Date: 2026-02-06 08:25:04.956473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '908bd075fcff'
down_revision: Union[str, None] = '8320d3e24dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('incident_number', sa.String(length=50), nullable=False, comment='Unique incident identifier (e.g., INC-2026-001)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short descriptive title of the incident'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed description of the incident'),
    sa.Column('incident_type', postgresql.ENUM('MALWARE', 'PHISHING', 'DATA_BREACH', 'DDOS', 'UNAUTHORIZED_ACCESS', 'INSIDER_THREAT', 'RANSOMWARE', 'UNKNOWN', 'OTHER', name='incident_type_enum'), nullable=False, comment='Type of security incident (malware, phishing, etc.)'),
    sa.Column('severity', postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='incident_severity_enum'), nullable=False, comment='Severity level (critical, high, medium, low)'),
    sa.Column('status', postgresql.ENUM('DETECTED', 'INVESTIGATING', 'CONTAINED', 'ERADICATED', 'RECOVERED', 'CLOSED', name='incident_status_enum'), nullable=False, comment='Current status in incident lifecycle'),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False, comment='When the incident was first detected'),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False, comment='When the incident was formally reported'),
    sa.Column('contained_at', sa.DateTime(timezone=True), nullable=True, comment='When the incident was contained'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='When the incident was fully resolved'),
    sa.Column('assigned_to', sa.String(length=255), nullable=True, comment='Email of assigned incident responder'),
    sa.Column('response_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured response plan steps'),
    sa.Column('actions_taken', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of executed response actions'),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Collected evidence (logs, screenshots, etc.)'),
    sa.Column('related_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of affected asset IDs'),
    sa.Column('impact_assessment', sa.Text(), nullable=True, comment='Assessment of incident impact on business'),
    sa.Column('root_cause', sa.Text(), nullable=True, comment='Root cause analysis findings'),
    sa.Column('lessons_learned', sa.Text(), nullable=True, comment='Lessons learned for future prevention'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_assigned_to'), 'incidents', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_incidents_detected_at'), 'incidents', ['detected_at'], unique=False)
    op.create_index('ix_incidents_detected_at_desc', 'incidents', ['detected_at'], unique=False, postgresql_ops={'detected_at': 'DESC'})
    op.create_index(op.f('ix_incidents_incident_number'), 'incidents', ['incident_number'], unique=True)
    op.create_index(op.f('ix_incidents_incident_type'), 'incidents', ['incident_type'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index('ix_incidents_severity_status', 'incidents', ['severity', 'status'], unique=False, postgresql_where="status != 'CLOSED'")
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_type_severity', 'incidents', ['incident_type', 'severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_type_severity', table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index('ix_incidents_severity_status', table_name='incidents', postgresql_where="status != 'CLOSED'")
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_number'), table_name='incidents')
    op.drop_index('ix_incidents_detected_at_desc', table_name='incidents', postgresql_ops={'detected_at': 'DESC'})
    op.drop_index(op.f('ix_incidents_detected_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_assigned_to'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
